name: sensor
description: Harper sensors
version: 0.0.1
author: Ji Young Lee & Ray King

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  async: "^1.10.0"
  csv: any
  firebase_rest: "^0.1.3"
  lookup_map: "^0.0.1"
  path: any
  stream_transformers: "^0.3.0+3"
  pub_semver: "^1.2.4"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
